### DISCUSSION TITLE
Seems that 'moveto' is no longer supported - how do you test hover actions?

### DISCUSSION THREAD

**Discussion by Saeven** [php-webdriver/php-webdriver#1044] [Q&A] [answered]
In the process of upgrading our Behat rig, we landed on this configuration and the latest ChromeDriver and selenium/standalone-chrome image.

```
    "behat/behat": "v3.12.0",
    "behat/mink": "v1.10.0",
    "behat/mink-extension": "2.3.1",
    "behat/mink-selenium2-driver": "1.6.0",
    "php-webdriver/webdriver": "1.13.1",
```

We noticed that this feature context no longer works:

```
 /**
     * @When /^I hover over the element "([^"]*)"$/
     */
    public function iHoverOverTheElement($locator)
    {
        $session = $this->getSession();
        $element = $session->getPage()->find('css', $locator);

        if (null === $element) {
            throw new \InvalidArgumentException(sprintf('No element matching "%s" could be found', $locator));
        }

        $element->mouseOver();
    }
```

The mouseOver action in Mink triggers `$this->getDriver()->mouseOver($this->getXpath());` which in turn results in logs such as:

```
22:31:45.759 WARN [SeleniumSpanExporter$1.lambda$export$1] - Unable to execute request for an existing session: POST /session/e7c2bdfafc03e7afa763268c81d9c4a1/moveto
```

Seems moveto is gone?  How do we go about testing hovers in this new spec?

Thanks for your guidance!

**Comment by andrewnicols** [comment]
HI @Saeven,

What version of Behat + Mink were you upgrading from?

We're not suing the official behat/mink-selenium2-driver, we use a driver we worked on with @oleg-andreyev: https://github.com/oleg-andreyev/MinkPhpWebDriver/

This is working fine for us with Behat 3.11.

Oleg's underlying `mouseOver` function uses the webDriver Action system and does the following:
```
        $element = $this->findElement($xpath);
        $this->webDriver->action()->moveToElement($element)->perform();
```
https://github.com/oleg-andreyev/MinkPhpWebDriver/blob/master/src/WebDriver.php#L899-L903

We'e been using this driver with Moodle for the past 2-3 years without any incident - we did spend a lot of time working together to get everything working with minimal backwards compatability issues.

The official Behat Selenium2 driver is very much abandoned. No changes in  eight years, and the official maintainer seems to have largely gone AWOL.

In any case, the solution here is to use the webDriver action factory above.

**Reply by Saeven** [reply]
Thanks for the response @andrewnicols.  We're upgrading from this configuration:

`selenium/standalone-chrome-debug:3.141.59-oxygen` using this configuration:

```
    "behat/behat": "3.6.1",
    "behat/mink": "1.8.1",
    "behat/mink-extension": "2.3.1",
    "behat/mink-selenium2-driver": "1.2.0",
    "instaclick/php-webdriver": "1.4.7",
```

This config works, but uses a much older version of Chrome.  Upgrading the selenium image forced our hand on the library upgrades, and that's when hover complete broke.  I've found a lot of gripes online about moveto being removed somewhere along the chain within Selenium; but no solutions.  I'll give the driver you've linked a try!

**Reply by Saeven** [reply]
Yeah unfortunately even with the two libs swapped in and the extension added to behat.yml, the problem persists:

```
    "oleg-andreyev/mink-phpwebdriver": "v1.2.1",
    "oleg-andreyev/mink-phpwebdriver-extension": "v1.0.0",
```

Seems hover got nuked from selenium at some point.   I'm going to try rolling selenium back until I find the version where they killed it.  Not being able to test hover is a bit of a show-stopper.

```
Unable to execute request for an existing session: POST \u002fsession\u002fdc6e223e5ebc84a10d8b157250c5ca20\u002fmoveto
```

**Comment by Saeven** [comment]
As added information, pertaining to version of selenium/standalone-chrome

| Selenium Version | ChromeDriver Version | Status |
| ----------------- | ---------------------- | ------- |
| 4.2                         |  103.0.5060.53             | works  |
| 4.3                         |  103.0.5060.134           | breaks |


4.4 and on break as well.  Looks like something was deprecated, that this entire ecosystem of drivers depends on somewhere in between these versions...

**Reply by andrewnicols** [reply]
Yes 4.3 deprecated legacy webdriver recently - a few months ago.

But the issue is in your driver in this case.

It's strange because the Oleg driver does not call moveto at all, which suggests that your config is wrong.

Note: You will have to update your behat.yml to modify the Driver extension details. Here's an excerpt of mine:
```
chrome:
  extensions:
    Behat\MinkExtension:
      webdriver:
        browser: chrome
        wd_host: 'http://localhost:4444/wd/hub'
        capabilities:
          extra_capabilities:
            chromeOptions:
              args:
                - disable-web-security
                - unlimited-storage
```

**Reply by Saeven** [reply]
@andrewnicols would you be open to sharing your entire behat.yml so that I can see how the pieces fit? 🙏🏼. The one I'm migrating from looks like so:

```
# behat.yml
default:
  autoload: [ '%paths.base%/../contexts' ]
  suites:
    core_features:
      paths: [ '%paths.base%/../features' ]
      contexts: [ FeatureContext, CirclicalBehatFixtures\Behat\DatabaseContext ]
  extensions:
    Lemonade\Service\Behat\TimeLoggerExtension:
      enabled_always: true
    Behat\MinkExtension:
      base_url: http://web:80
      files_path: '%paths.base%/../../../public/assets/'
      javascript_session: selenium2
      browser_name: chrome
      selenium2:
        browser: chrome
        capabilities:
          browserName: "chrome"
          browser: "chrome"
          marionette: false
```

To clarify, here are all my behat-y things in composer.json

```
    "behat/behat": "v3.12.0",
    "behat/mink": "v1.10.0",
    "behat/mink-extension": "2.3.1",
    "oleg-andreyev/mink-phpwebdriver": "v1.2.1",
    "oleg-andreyev/mink-phpwebdriver-extension": "v1.0.0",
```

Greatly appreciated.

**Reply by Saeven** [reply]
@andrewnicols as added detail, the reason I ask, is that if I change my behat.yml as was recommended (combined with the test [at this URL](https://github.com/oleg-andreyev/MinkPhpWebdriverExtension/blob/main/tests/OAndreyev/MinkPhpWebdriverExtension/Tests/Integration/behat.yml)) to create something like this:

```
default:
  autoload: [ '%paths.base%/../contexts' ]
  suites:
    core_features:
      paths: [ '%paths.base%/../features' ]
      contexts: [ FeatureContext, CirclicalBehatFixtures\Behat\DatabaseContext ]
  extensions:
    OAndreyev\MinkPhpWebdriverExtension: ~
    Behat\MinkExtension:
      default_session: webdriver
      webdriver:
        wd_host: "http://web:80"
        browser: "chrome"
        capabilities:
          extra_capabilities:
            chromeOptions:
              args:
                - disable-web-security
                - unlimited-storage
```

Then I am left with a multitude of these errors:

```
    BeforeScenario # FeatureContext::beforeScenario()
      Could not open connection: Curl error thrown for http POST to /session with params: {"capabilities":{"firstMatch":[{"browserName":"chrome","goog:chromeOptions":{"args":["disable-web-security","unlimited-storage"]}}]},"desiredCapabilities":{"browserName":"chrome","platform":"ANY","tags":["SaevenPro.local","PHP 7.4.33"],"chromeOptions":{"args":["disable-web-security","unlimited-storage"]},"browser":"firefox","marionette":null,"ignoreZoomSetting":false,"name":"Behat feature suite"}}
      
      Could not resolve host: web (Behat\Mink\Exception\DriverException)
```

It conversely 'works' with the original configuration, despite moveto being a problem.
