### DISCUSSION TITLE
webdriver-firefox profile directory and select profile

### DISCUSSION THREAD

**Discussion by grekpg** [php-webdriver/php-webdriver#869] [Q&A]
I try many options but always have /tmp/rust_mozprofileXYZ profile

I link local folder to firefox container and try select it.

Also i try create profile in container and simple select it.

All fail

here is start log why always is rust_mozprofileXXXX

$host = 'selenium-hub:4444/wd/hub';
        $web_driver = RemoteWebDriver::create(
            $host,
            $capabilities
        );

```
mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "--marionette" "-foreground" 
"-no-remote" "-profile" "/tmp/rust_mozprofile8Q4N0k"

```
here is some examples :

```
 $firefoxProfile = new FirefoxProfile('/home/seluser/.mozilla/firefox/t5umgtio.test2');
//        $firefoxProfile->setPreference("webdriver.firefox.profile",'/home/seluser/.mozilla/firefox/t5umgtio.test2');
        $firefoxProfile->setPreference("browser.download.downloadDir",'/home/seluser');
        $firefoxProfile->setPreference("webdriver.firefox.profile",'test2');
        $firefoxProfile->setPreference("-profile",'/home/seluser/.mozilla/firefox/t5umgtio.test2');
        $firefoxProfile->setPreference("-firefoxProfileTemplate",'/home/seluser/.mozilla/firefox/');
        $firefoxProfile->setPreference("-Dwebdriver.firefox.profile",'test2');

        $capabilities = DesiredCapabilities::firefox ();
//        $capabilities->setCapability(FirefoxDriver::PROFILE, $firefoxProfile);
//        $capabilities->setCapability('acceptSslCerts', false);
        $capabilities->setCapability('--marionette', false);
        $capabilities->setCapability("Dwebdriver.firefox.profile", 'test2');
        $capabilities->setCapability("-firefoxProfileTemplate", '/home/seluser/.mozilla/firefox/');
        $capabilities->setCapability("-profile", 'test2');
        $capabilities->setCapability("profile", 'test2');
        $capabilities->setCapability("firefoxProfileTemplate", 'test2');
//        $capabilities->setCapability('-profile', '/home/seluser/.mozilla/firefox/t5umgtio.test2');
//        $capabilities->setCapability('--profile', '/home/seluser/.mozilla/firefox/t5umgtio.test2');

        $web_driver = RemoteWebDriver::create(
            $host,
            $capabilities
        );
```

I using docker-compose

```
 firefox-hub:
      image: selenium/node-firefox-debug
      container_name: firefox-hub
      depends_on:
        - selenium-hub
      environment:
        - SCREEN_WIDTH=1024
        - SCREEN_HEIGHT=800
        - HUB_PORT_4444_TCP_ADDR=selenium-hub
        - HUB_PORT_4444_TCP_PORT=4444
        - NODE_MAX_SESSION=10
        - NODE_MAX_INSTANCES=10
        - SE_EVENT_BUS_HOST=selenium-hub
        - SE_EVENT_BUS_PUBLISH_PORT=4444
        - GRID_DEBUG=true
      volumes:
        - /dev/shm:/dev/shm
        - ./var/firefox-profiles:/home/seluser/.mozilla/firefox
```

i dont know that is correct but in logs i see something like that

`"-firefoxProfileTemplate": "\u002fhome\u002fseluser\u002f.mozilla\u002ffirefox\u002f",`

also i try chrome without success 

In chrome in log i see that 
10:52:26.934 INFO [ActiveSessionFactory.apply] - Capabilities are: {
 "browserName": "chrome",
 "chromeOptions": {
 "args": [
"user-data-dir=\u002fhome\u002fseluser\u002f.config\u002fgoogle-chrome\u002f",
"--user-data-dir=\u002fhome\u002fseluser\u002f.config\u002fgoogle-chrome\u002f",
"--profile-directory=grekClient",

maybe \u002f is problem ? 
i setup 
 $options->addArguments([
            "user-data-dir=/home/seluser/.config/google-chrome/",
            "--user-data-dir=/home/seluser/.config/google-chrome/",

Any help ?
