### ISSUE TITLE
With 4.18.1-20240224 I get a DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by elnath78** [php-webdriver/php-webdriver#1094]
### Bug description

Fatal error: Uncaught Facebook\WebDriver\Exception\SessionNotCreatedException: Could not start a new session. Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: session not created: DevToolsActivePort file doesn't exist Host info: host: 'd1a93cda54a8', ip: '172.18.0.5' Build info: version: '4.18.1', revision: 'b1d3319b48' System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.5.0-25-generic', java.version: '11.0.21' Driver info: driver.version: unknown Build info: version: '4.18.1', revision: 'b1d3319b48' System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.5.0-25-generic', java.version: '11.0.21' Driver info: driver.version: unknown Build info: version: '4.18.1', revision: 'b1d3319b48' System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.5.0-25-generic', java.version: '11.0.21' Driver info: driver.version: unknown in C:\xampp\htdocs\redacted\vendor\php-webdriver\webdriver\lib\Exception\WebDriverException.php on line 130

### How could the issue be reproduced

```shell
//Set Up Chrome Options
$chromeOptions = new ChromeOptions();
$chromeOptions->setExperimentalOption('w3c', false);
$chromeOptions->addArguments($args);
//Set Capabilities
$seleniumCapabilities = DesiredCapabilities::chrome();
$seleniumCapabilities->setCapability('acceptSslCerts', false);
//Create Selenium Connection
$driver = RemoteWebDriver::create($seleniumHost, $seleniumCapabilities);
//Go To URL
$url="https://en.wikipedia.org/wiki/Selenium_(software)";
$driver->navigate()->to($url);
//Exit, do nothing just pray connection works
$driver->quit();
```

### Expected behavior

I'd be happy if I can set a connection, would be a great upgrade.

### Php-webdriver version

1.15.1

### PHP version

8.2.0

### How do you start the browser driver or Selenium server

selenium in docker

### Selenium server / Selenium Docker image version

4.18.1-20240224

### Browser driver (chromedriver/geckodriver...) version

where should I run this?

### Browser name and version

where should I run this?

### Operating system

Ubuntu

### Additional context

```yml
# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3.yml down`
version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.18.1-20240224
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  edge:
    image: selenium/node-edge:4.18.1-20240224
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.18.1-20240224
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.18.1-20240224
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```
