### ISSUE TITLE
excludeswitches parameter is not valid

### ISSUE THREAD

**Issue by HeJiaNong** [php-webdriver/php-webdriver#778]
### What are you trying to achieve? (Expected behavior)
`window.navigator.webdriver` is `false`

### What do you get instead? (Actual behavior)
`window.navigator.webdriver` is `true`

### How could the issue be reproduced? (Steps to reproduce)

I found a way to prevent selenium from being detected. I tried to set the excludeswitches parameter, but it was invalid

docker-compose.yml
```
  selenium-standalone-chrome:
    image: selenium/standalone-chrome-debug:3.141.59-20200326
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 5444:4444
      - 5999:5900
```

php
```php
    $session = RemoteWebDriver::create(
        'selenium-standalone-chrome:4444/wd/hub',
        DesiredCapabilities::chrome()
            ->setCapability(
                ChromeOptions::CAPABILITY,
                (new ChromeOptions())->setExperimentalOption('excludeSwitches', ['enable-automation'])
            )
    );

    var_dump($session->executeScript('return window.navigator.webdriver'));

    $session->quit();
```

result is `bool(true)`

### Details

* Php-webdriver version: `"php-webdriver/webdriver": "^1.8"`
* PHP version: docker image `php:7.4-fpm`
* Selenium server version: docker image `selenium/standalone-chrome-debug:3.141.59-20200326`
* Operating system: mac os 10.15
* Browser used + version:
