### ISSUE TITLE
Proxy auth fails from example page

### ISSUE THREAD

**Issue by fissben** [php-webdriver/php-webdriver#885]
### Bug description
Proxy with auth not working. Used this page as example https://github.com/php-webdriver/php-webdriver/wiki/HowTo-Work-with-proxy

Selenium constantly logging error like this:
`Response code 400. Message: httpProxy is not of the form host[:port]: cleared_user:cleared_password@cleared_ip:cleared_port`

Which is fair enough according to java doc https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/Proxy.html#setHttpProxy(java.lang.String)

### How could the issue be reproduced

1. add `WebDriverCapabilityType::PROXY` caps according to example page

```php
namespace Facebook\WebDriver;

use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;
use Facebook\WebDriver\Remote\WebDriverCapabilityType;

require_once('vendor/autoload.php');

$host = 'http://localhost:4444/wd/hub';
$proxyUrl = 'user:pass@proxy_host:proxy_port';

$caps = DesiredCapabilities::firefox();
$caps->setCapability(WebDriverCapabilityType::PROXY, [
    'proxyType' => 'manual',
    'httpProxy' => $proxyUrl,
    'sslProxy' => $proxyUrl,
]);

$driver = RemoteWebDriver::create($host, $caps);
$driver->get("https://2ip.ru");
sleep(2);
$driver->takeScreenshot("2ip.jpeg");


$driver->close();
$driver->quit();
```

```html
<!--no html-->
```

### Expected behavior
WebDriver should connect to site 2ip.ru through proxy

### Details

* Php-webdriver version: 1.10
* PHP version: 7.3.25
* How do you start the browser: docker-hub+firefox node
* Selenium server version: 4.0.0-beta-3
* Operating system: MacOS with docker 
* Browser used + version: Firefox 
* Browser driver (firefox) version: n/a

### Additional context
docker-compose.yml
```yml
version: "3"
services:
  firefox:
    image: selenium/node-firefox:4.0.0-beta-3-prerelease-20210402
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  selenium-hub:
    image: selenium/hub:4.0.0-beta-3-prerelease-20210402
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"


```
